-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id bigint NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass),
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  user_name character varying DEFAULT 'Anonymous'::character varying,
  user_role character varying DEFAULT 'anonymous'::character varying,
  action character varying NOT NULL,
  module character varying NOT NULL,
  record_id character varying,
  record_type character varying,
  description text NOT NULL,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  session_id character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.barangay_codes (
  id integer NOT NULL DEFAULT nextval('barangay_codes_id_seq'::regclass),
  barangay_name character varying NOT NULL UNIQUE,
  barangay_code character varying NOT NULL UNIQUE,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT barangay_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.distribution_records (
  id integer NOT NULL DEFAULT nextval('distribution_records_id_seq'::regclass),
  request_id integer NOT NULL,
  distribution_date date DEFAULT CURRENT_DATE,
  fertilizer_type character varying,
  fertilizer_bags_given integer,
  seed_type character varying,
  seed_kg_given numeric,
  voucher_code character varying UNIQUE,
  qr_code_data text,
  claimed boolean DEFAULT false,
  claim_date timestamp without time zone,
  farmer_signature boolean DEFAULT false,
  verified_by integer,
  verification_notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT distribution_records_pkey PRIMARY KEY (id),
  CONSTRAINT distribution_records_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.farmer_requests(id)
);
CREATE TABLE public.farm_parcels (
  id integer NOT NULL DEFAULT nextval('farm_parcels_id_seq'::regclass),
  submission_id integer NOT NULL,
  parcel_number character varying NOT NULL,
  farm_location_barangay character varying,
  farm_location_city_municipality character varying,
  total_farm_area_ha numeric NOT NULL CHECK (total_farm_area_ha >= 0::numeric),
  within_ancestral_domain boolean DEFAULT false,
  ownership_document_no character varying,
  agrarian_reform_beneficiary boolean DEFAULT false,
  ownership_type_registered_owner boolean DEFAULT false,
  ownership_type_tenant boolean DEFAULT false,
  ownership_type_lessee boolean DEFAULT false,
  tenant_land_owner_name character varying,
  lessee_land_owner_name character varying,
  ownership_others_specify character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT farm_parcels_pkey PRIMARY KEY (id),
  CONSTRAINT farm_parcels_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.rsbsa_submission(id)
);
CREATE TABLE public.farmer_requests (
  id integer NOT NULL DEFAULT nextval('farmer_requests_id_seq'::regclass),
  season character varying NOT NULL,
  request_date date DEFAULT CURRENT_DATE,
  farmer_id integer,
  farmer_name character varying NOT NULL,
  barangay character varying,
  farm_area_ha numeric NOT NULL,
  crop_type character varying,
  ownership_type character varying,
  num_parcels integer DEFAULT 1,
  fertilizer_requested boolean DEFAULT false,
  seeds_requested boolean DEFAULT false,
  request_notes text,
  priority_score integer DEFAULT 0,
  priority_rank integer,
  assigned_fertilizer_type character varying,
  assigned_fertilizer_bags integer,
  assigned_seed_type character varying,
  assigned_seed_kg numeric,
  fertilizer_accepted boolean,
  seeds_accepted boolean,
  rejection_reason text,
  status character varying DEFAULT 'pending'::character varying,
  created_by integer,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  requested_urea_bags numeric DEFAULT 0,
  requested_complete_14_bags numeric DEFAULT 0,
  requested_complete_16_bags numeric DEFAULT 0,
  requested_ammonium_sulfate_bags numeric DEFAULT 0,
  requested_ammonium_phosphate_bags numeric DEFAULT 0,
  requested_muriate_potash_bags numeric DEFAULT 0,
  requested_jackpot_kg numeric DEFAULT 0,
  requested_us88_kg numeric DEFAULT 0,
  requested_th82_kg numeric DEFAULT 0,
  requested_rh9000_kg numeric DEFAULT 0,
  requested_lumping143_kg numeric DEFAULT 0,
  requested_lp296_kg numeric DEFAULT 0,
  allocation_id integer,
  requested_zinc_sulfate_bags numeric DEFAULT 0,
  requested_vermicompost_bags numeric DEFAULT 0,
  requested_chicken_manure_bags numeric DEFAULT 0,
  requested_rice_straw_kg numeric DEFAULT 0,
  requested_carbonized_rice_hull_bags numeric DEFAULT 0,
  requested_biofertilizer_liters numeric DEFAULT 0,
  requested_nanobiofertilizer_liters numeric DEFAULT 0,
  requested_organic_root_exudate_mix_liters numeric DEFAULT 0,
  requested_azolla_microphylla_kg numeric DEFAULT 0,
  requested_foliar_liquid_fertilizer_npk_liters numeric DEFAULT 0,
  requested_rice_seeds_nsic_rc160_kg numeric DEFAULT 0,
  requested_rice_seeds_nsic_rc222_kg numeric DEFAULT 0,
  requested_mestiso_1_kg numeric DEFAULT 0,
  requested_mestiso_20_kg numeric DEFAULT 0,
  requested_mestiso_29_kg numeric DEFAULT 0,
  requested_mestiso_55_kg numeric DEFAULT 0,
  requested_mestiso_73_kg numeric DEFAULT 0,
  requested_mestiso_99_kg numeric DEFAULT 0,
  requested_mestiso_103_kg numeric DEFAULT 0,
  requested_nsic_rc402_kg numeric DEFAULT 0,
  requested_nsic_rc480_kg numeric DEFAULT 0,
  requested_nsic_rc216_kg numeric DEFAULT 0,
  requested_nsic_rc218_kg numeric DEFAULT 0,
  requested_nsic_rc506_kg numeric DEFAULT 0,
  requested_nsic_rc508_kg numeric DEFAULT 0,
  requested_nsic_rc512_kg numeric DEFAULT 0,
  requested_nsic_rc534_kg numeric DEFAULT 0,
  requested_tubigan_28_kg numeric DEFAULT 0,
  requested_tubigan_30_kg numeric DEFAULT 0,
  requested_tubigan_22_kg numeric DEFAULT 0,
  requested_sahod_ulan_2_kg numeric DEFAULT 0,
  requested_sahod_ulan_10_kg numeric DEFAULT 0,
  requested_salinas_6_kg numeric DEFAULT 0,
  requested_salinas_7_kg numeric DEFAULT 0,
  requested_salinas_8_kg numeric DEFAULT 0,
  requested_malagkit_5_kg numeric DEFAULT 0,
  requested_corn_seeds_hybrid_kg numeric DEFAULT 0,
  requested_corn_seeds_opm_kg numeric DEFAULT 0,
  requested_vegetable_seeds_kg numeric DEFAULT 0,
  requested_np_16_20_0_bags numeric DEFAULT 0,
  requested_rice_seeds_nsic_rc440_kg numeric DEFAULT 0,
  CONSTRAINT farmer_requests_pkey PRIMARY KEY (id),
  CONSTRAINT farmer_requests_farmer_id_fkey FOREIGN KEY (farmer_id) REFERENCES public.rsbsa_submission(id),
  CONSTRAINT fk_farmer_requests_allocation FOREIGN KEY (allocation_id) REFERENCES public.regional_allocations(id)
);
CREATE TABLE public.land_history (
  id integer NOT NULL DEFAULT nextval('land_history_id_seq'::regclass),
  land_parcel_id integer,
  parcel_number character varying,
  farm_location_barangay character varying,
  farm_location_municipality character varying DEFAULT 'Dumangas'::character varying,
  total_farm_area_ha numeric,
  farmer_id integer,
  farmer_name character varying,
  farmer_ffrs_code character varying,
  is_registered_owner boolean DEFAULT false,
  is_tenant boolean DEFAULT false,
  is_lessee boolean DEFAULT false,
  land_owner_id integer,
  land_owner_name character varying,
  period_start_date date NOT NULL,
  period_end_date date,
  is_current boolean DEFAULT true,
  change_type character varying NOT NULL DEFAULT 'NEW'::character varying,
  change_reason text,
  previous_history_id integer,
  rsbsa_submission_id integer,
  within_ancestral_domain boolean DEFAULT false,
  agrarian_reform_beneficiary boolean DEFAULT false,
  ownership_document_no character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by character varying,
  notes text,
  farm_parcel_id bigint,
  land_owner_ffrs_code character varying,
  tenant_name character varying,
  tenant_ffrs_code character varying,
  lessee_name character varying,
  lessee_ffrs_code character varying,
  is_other_ownership boolean DEFAULT false,
  transferred_area_ha numeric,
  remaining_area_ha numeric,
  ownership_category text,
  CONSTRAINT land_history_pkey PRIMARY KEY (id),
  CONSTRAINT land_history_land_parcel_id_fkey FOREIGN KEY (land_parcel_id) REFERENCES public.land_parcels(id),
  CONSTRAINT land_history_previous_history_id_fkey FOREIGN KEY (previous_history_id) REFERENCES public.land_history(id)
);
CREATE TABLE public.land_parcels (
  id integer NOT NULL DEFAULT nextval('land_parcels_id_seq'::regclass),
  parcel_number character varying NOT NULL UNIQUE,
  farm_location_barangay character varying,
  farm_location_municipality character varying DEFAULT 'Dumangas'::character varying,
  farm_location_province character varying DEFAULT 'Iloilo'::character varying,
  total_farm_area_ha numeric,
  within_ancestral_domain boolean DEFAULT false,
  agrarian_reform_beneficiary boolean DEFAULT false,
  ownership_document_no character varying,
  ownership_document_type character varying,
  latitude numeric,
  longitude numeric,
  polygon_coordinates jsonb,
  land_type character varying,
  primary_crop character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_by character varying,
  CONSTRAINT land_parcels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.land_plots (
  id character varying NOT NULL,
  name character varying,
  ffrs_id character varying,
  area numeric,
  coordinate_accuracy character varying,
  barangay character varying,
  first_name character varying,
  middle_name character varying,
  surname character varying,
  ext_name character varying,
  gender character varying,
  municipality character varying,
  province character varying,
  parcel_address text,
  status character varying,
  street character varying,
  farm_type character varying,
  plot_source character varying,
  parcel_number character varying,
  geometry jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  geometry_postgis USER-DEFINED,
  farmer_id integer,
  CONSTRAINT land_plots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.owner_link_backfill_audit (
  id bigint NOT NULL DEFAULT nextval('owner_link_backfill_audit_id_seq'::regclass),
  farm_parcel_id bigint NOT NULL,
  link_type text NOT NULL CHECK (link_type = ANY (ARRAY['tenant'::text, 'lessee'::text])),
  owner_name text,
  farm_location_barangay text,
  candidate_count integer NOT NULL DEFAULT 0,
  reason text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT owner_link_backfill_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ownership_category_exception_audit (
  id bigint NOT NULL DEFAULT nextval('ownership_category_exception_audit_id_seq'::regclass),
  source_table text NOT NULL CHECK (source_table = ANY (ARRAY['rsbsa_submission'::text, 'rsbsa_farm_parcels'::text, 'land_history'::text])),
  source_id bigint NOT NULL,
  reason_code text NOT NULL,
  reason_detail text NOT NULL,
  legacy_registered_owner boolean,
  legacy_tenant boolean,
  legacy_lessee boolean,
  existing_ownership_category text,
  suggested_ownership_category text,
  capture_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  resolved boolean NOT NULL DEFAULT false,
  resolved_at timestamp with time zone,
  resolution_notes text,
  detected_at timestamp with time zone NOT NULL DEFAULT now(),
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ownership_category_exception_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ownership_metrics_snapshots (
  id bigint NOT NULL DEFAULT nextval('ownership_metrics_snapshots_id_seq'::regclass),
  captured_at timestamp with time zone NOT NULL DEFAULT now(),
  capture_label text NOT NULL DEFAULT 'manual'::text,
  metrics jsonb NOT NULL,
  CONSTRAINT ownership_metrics_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ownership_transfer_items (
  id bigint NOT NULL DEFAULT nextval('ownership_transfer_items_id_seq'::regclass),
  transfer_id bigint NOT NULL,
  land_parcel_id integer NOT NULL,
  land_history_id integer,
  parcel_number character varying,
  farm_location_barangay character varying,
  donor_area_ha numeric NOT NULL,
  transferred_area_ha numeric NOT NULL,
  scope text NOT NULL DEFAULT 'take_all'::text CHECK (scope = ANY (ARRAY['take_all'::text, 'partial'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ownership_transfer_items_pkey PRIMARY KEY (id),
  CONSTRAINT ownership_transfer_items_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.ownership_transfers(id),
  CONSTRAINT ownership_transfer_items_land_parcel_id_fkey FOREIGN KEY (land_parcel_id) REFERENCES public.land_parcels(id),
  CONSTRAINT ownership_transfer_items_land_history_id_fkey FOREIGN KEY (land_history_id) REFERENCES public.land_history(id)
);
CREATE TABLE public.ownership_transfer_proof_recovery_queue (
  id bigint NOT NULL DEFAULT nextval('ownership_transfer_proof_recovery_queue_id_seq'::regclass),
  transfer_id bigint NOT NULL,
  storage_bucket text NOT NULL,
  storage_path text NOT NULL,
  file_name text,
  mime_type text,
  file_size_bytes bigint,
  object_created_at timestamp with time zone,
  transfer_created_at timestamp with time zone,
  second_diff bigint,
  match_confidence text NOT NULL CHECK (match_confidence = ANY (ARRAY['HIGH'::text, 'REVIEW'::text])),
  match_reason text NOT NULL,
  approval_status text NOT NULL DEFAULT 'PENDING'::text CHECK (approval_status = ANY (ARRAY['PENDING'::text, 'APPROVED'::text, 'REJECTED'::text, 'APPLIED'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ownership_transfer_proof_recovery_queue_pkey PRIMARY KEY (id),
  CONSTRAINT ownership_transfer_proof_recovery_queue_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.ownership_transfers(id)
);
CREATE TABLE public.ownership_transfer_proofs (
  id bigint NOT NULL DEFAULT nextval('ownership_transfer_proofs_id_seq'::regclass),
  transfer_id bigint NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'ownership-transfer-proofs'::text,
  storage_path text NOT NULL,
  image_url text,
  file_name text,
  mime_type text CHECK (mime_type IS NULL OR (mime_type = ANY (ARRAY['image/png'::text, 'image/jpeg'::text, 'image/jpg'::text]))),
  file_size_bytes bigint,
  uploaded_by uuid DEFAULT auth.uid(),
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT ownership_transfer_proofs_pkey PRIMARY KEY (id),
  CONSTRAINT ownership_transfer_proofs_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.ownership_transfers(id)
);
CREATE TABLE public.ownership_transfers (
  id bigint NOT NULL DEFAULT nextval('ownership_transfers_id_seq'::regclass),
  transfer_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  transfer_mode text DEFAULT 'voluntary'::text CHECK (transfer_mode = ANY (ARRAY['voluntary'::text, 'inheritance'::text])),
  source_role text DEFAULT 'registered_owner'::text CHECK (source_role = ANY (ARRAY['registered_owner'::text, 'tenant'::text, 'lessee'::text])),
  from_farmer_id bigint,
  to_farmer_id bigint,
  transfer_date date DEFAULT CURRENT_DATE,
  transfer_reason text,
  area_mode text DEFAULT 'take_all'::text CHECK (area_mode = ANY (ARRAY['take_all'::text, 'partial'::text])),
  area_requested_ha numeric,
  area_available_ha numeric,
  is_deceased_confirmed boolean NOT NULL DEFAULT false,
  status text DEFAULT 'applied'::text CHECK (status = ANY (ARRAY['applied'::text, 'cancelled'::text])),
  registry_applied boolean NOT NULL DEFAULT false,
  created_by uuid DEFAULT auth.uid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  applied_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  transfer_type text,
  documents jsonb DEFAULT '[]'::jsonb,
  notes text,
  CONSTRAINT ownership_transfers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ot_from_farmer FOREIGN KEY (from_farmer_id) REFERENCES public.rsbsa_submission(id),
  CONSTRAINT fk_ot_to_farmer FOREIGN KEY (to_farmer_id) REFERENCES public.rsbsa_submission(id)
);
CREATE TABLE public.regional_allocations (
  id integer NOT NULL DEFAULT nextval('regional_allocations_id_seq'::regclass),
  season character varying NOT NULL,
  allocation_date date DEFAULT CURRENT_DATE,
  season_start_date date,
  season_end_date date,
  urea_46_0_0_bags integer DEFAULT 0,
  complete_14_14_14_bags integer DEFAULT 0,
  ammonium_sulfate_21_0_0_bags integer DEFAULT 0,
  np_16_20_0_bags integer DEFAULT 0,
  muriate_potash_0_0_60_bags integer DEFAULT 0,
  rice_seeds_nsic_rc160_kg numeric DEFAULT 0,
  rice_seeds_nsic_rc222_kg numeric DEFAULT 0,
  notes text,
  status character varying DEFAULT 'active'::character varying,
  created_by integer,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  jackpot_kg numeric DEFAULT 0,
  us88_kg numeric DEFAULT 0,
  th82_kg numeric DEFAULT 0,
  rh9000_kg numeric DEFAULT 0,
  lumping143_kg numeric DEFAULT 0,
  lp296_kg numeric DEFAULT 0,
  zinc_sulfate_bags numeric NOT NULL DEFAULT 0.00,
  vermicompost_bags numeric NOT NULL DEFAULT 0.00,
  chicken_manure_bags numeric NOT NULL DEFAULT 0.00,
  rice_straw_kg numeric NOT NULL DEFAULT 0.00,
  carbonized_rice_hull_bags numeric NOT NULL DEFAULT 0.00,
  biofertilizer_liters numeric NOT NULL DEFAULT 0.00,
  nanobiofertilizer_liters numeric NOT NULL DEFAULT 0.00,
  organic_root_exudate_mix_liters numeric NOT NULL DEFAULT 0.00,
  azolla_microphylla_kg numeric NOT NULL DEFAULT 0.00,
  foliar_liquid_fertilizer_npk_liters numeric NOT NULL DEFAULT 0.00,
  mestiso_1_kg numeric NOT NULL DEFAULT 0.00,
  mestiso_20_kg numeric NOT NULL DEFAULT 0.00,
  mestiso_29_kg numeric NOT NULL DEFAULT 0.00,
  mestiso_55_kg numeric NOT NULL DEFAULT 0.00,
  mestiso_73_kg numeric NOT NULL DEFAULT 0.00,
  mestiso_99_kg numeric NOT NULL DEFAULT 0.00,
  mestiso_103_kg numeric NOT NULL DEFAULT 0.00,
  nsic_rc402_kg numeric NOT NULL DEFAULT 0.00,
  nsic_rc480_kg numeric NOT NULL DEFAULT 0.00,
  nsic_rc216_kg numeric NOT NULL DEFAULT 0.00,
  nsic_rc218_kg numeric NOT NULL DEFAULT 0.00,
  nsic_rc506_kg numeric NOT NULL DEFAULT 0.00,
  nsic_rc508_kg numeric NOT NULL DEFAULT 0.00,
  nsic_rc512_kg numeric NOT NULL DEFAULT 0.00,
  nsic_rc534_kg numeric NOT NULL DEFAULT 0.00,
  tubigan_28_kg numeric NOT NULL DEFAULT 0.00,
  tubigan_30_kg numeric NOT NULL DEFAULT 0.00,
  tubigan_22_kg numeric NOT NULL DEFAULT 0.00,
  sahod_ulan_2_kg numeric NOT NULL DEFAULT 0.00,
  sahod_ulan_10_kg numeric NOT NULL DEFAULT 0.00,
  salinas_6_kg numeric NOT NULL DEFAULT 0.00,
  salinas_7_kg numeric NOT NULL DEFAULT 0.00,
  salinas_8_kg numeric NOT NULL DEFAULT 0.00,
  malagkit_5_kg numeric NOT NULL DEFAULT 0.00,
  ammonium_phosphate_16_20_0_bags integer DEFAULT 0,
  complete_16_16_16_bags integer DEFAULT 0,
  corn_seeds_hybrid_kg integer DEFAULT 0,
  corn_seeds_opm_kg integer DEFAULT 0,
  vegetable_seeds_kg integer DEFAULT 0,
  nsic_rc160_kg integer DEFAULT 0,
  nsic_rc222_kg integer DEFAULT 0,
  rice_seeds_nsic_rc440_kg integer DEFAULT 0,
  CONSTRAINT regional_allocations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rsbsa_farm_parcels (
  id bigint NOT NULL DEFAULT nextval('rsbsa_farm_parcels_id_seq'::regclass),
  submission_id bigint,
  parcel_number character varying NOT NULL,
  farm_location_barangay character varying,
  farm_location_municipality character varying,
  total_farm_area_ha numeric,
  within_ancestral_domain character varying CHECK (within_ancestral_domain::text = ANY (ARRAY['Yes'::character varying::text, 'No'::character varying::text])),
  ownership_document_no character varying,
  agrarian_reform_beneficiary character varying CHECK (agrarian_reform_beneficiary::text = ANY (ARRAY['Yes'::character varying::text, 'No'::character varying::text])),
  ownership_type_registered_owner boolean DEFAULT false,
  ownership_type_tenant boolean DEFAULT false,
  ownership_type_lessee boolean DEFAULT false,
  ownership_type_others boolean DEFAULT false,
  tenant_land_owner_name character varying,
  lessee_land_owner_name character varying,
  ownership_others_specify text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  tenant_land_owner_id bigint,
  lessee_land_owner_id bigint,
  is_current_owner boolean DEFAULT true,
  parent_parcel_id integer,
  split_origin_area_ha numeric,
  ownership_category text,
  cultivator_submission_id bigint,
  is_cultivating boolean NOT NULL DEFAULT true,
  cultivation_status_updated_at timestamp with time zone,
  cultivation_status_reason text,
  CONSTRAINT rsbsa_farm_parcels_pkey PRIMARY KEY (id),
  CONSTRAINT rsbsa_farm_parcels_cultivator_submission_id_fkey FOREIGN KEY (cultivator_submission_id) REFERENCES public.rsbsa_submission(id),
  CONSTRAINT fk_lessee_land_owner FOREIGN KEY (lessee_land_owner_id) REFERENCES public.rsbsa_submission(id),
  CONSTRAINT fk_tenant_land_owner FOREIGN KEY (tenant_land_owner_id) REFERENCES public.rsbsa_submission(id),
  CONSTRAINT rsbsa_farm_parcels_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.rsbsa_submission(id),
  CONSTRAINT rsbsa_farm_parcels_parent_parcel_id_fkey FOREIGN KEY (parent_parcel_id) REFERENCES public.rsbsa_farm_parcels(id),
  CONSTRAINT fk_rsbsa_farm_parcels_tenant_land_owner_id FOREIGN KEY (tenant_land_owner_id) REFERENCES public.rsbsa_submission(id),
  CONSTRAINT fk_rsbsa_farm_parcels_lessee_land_owner_id FOREIGN KEY (lessee_land_owner_id) REFERENCES public.rsbsa_submission(id)
);
CREATE TABLE public.rsbsa_submission (
  id bigint NOT NULL DEFAULT nextval('rsbsa_submission_id_seq'::regclass),
  LAST NAME character varying,
  FIRST NAME character varying,
  MIDDLE NAME character varying,
  EXT NAME character varying,
  GENDER character varying,
  BIRTHDATE date,
  BARANGAY character varying,
  MUNICIPALITY character varying,
  FARM LOCATION character varying,
  PARCEL AREA text,
  MAIN LIVELIHOOD character varying,
  OWNERSHIP_TYPE_REGISTERED_OWNER boolean DEFAULT false,
  OWNERSHIP_TYPE_TENANT boolean DEFAULT false,
  OWNERSHIP_TYPE_LESSEE boolean DEFAULT false,
  status character varying DEFAULT 'Submitted'::character varying,
  submitted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  TOTAL FARM AREA numeric,
  FFRS_CODE character varying UNIQUE,
  age integer,
  FARMER_RICE boolean DEFAULT false,
  FARMER_CORN boolean DEFAULT false,
  FARMER_OTHER_CROPS boolean DEFAULT false,
  FARMER_OTHER_CROPS_TEXT text,
  FARMER_LIVESTOCK boolean DEFAULT false,
  FARMER_LIVESTOCK_TEXT text,
  FARMER_POULTRY boolean DEFAULT false,
  FARMER_POULTRY_TEXT text,
  archived_at timestamp with time zone,
  archive_reason text,
  ownership_category text,
  status_change_reason text,
  CONSTRAINT rsbsa_submission_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shortages_fertilizer_role_fallback (
  nutrient_role text NOT NULL,
  fallback_fertilizer_id text NOT NULL,
  sort_order integer NOT NULL DEFAULT 1000,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shortages_fertilizer_role_fallback_pkey PRIMARY KEY (nutrient_role, fallback_fertilizer_id),
  CONSTRAINT shortages_fertilizer_role_fallback_fallback_fertilizer_id_fkey FOREIGN KEY (fallback_fertilizer_id) REFERENCES public.shortages_fertilizers(id)
);
CREATE TABLE public.shortages_fertilizers (
  id text NOT NULL,
  name text NOT NULL,
  category text,
  tier integer NOT NULL,
  nutrient_role text,
  nutrient_type text,
  application_timing text,
  form text,
  description text,
  sort_order integer NOT NULL DEFAULT 1000,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shortages_fertilizers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shortages_role_bridge (
  from_role text NOT NULL,
  to_role text NOT NULL,
  sort_order integer NOT NULL DEFAULT 1000,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shortages_role_bridge_pkey PRIMARY KEY (from_role, to_role)
);
CREATE TABLE public.shortages_seeds (
  id text NOT NULL,
  name text NOT NULL,
  category text,
  nsic_code text,
  yield_display text,
  yield_min_tha numeric,
  yield_max_tha numeric,
  maturity_days integer,
  environment text,
  status text,
  fertilizer_responsiveness_rank integer,
  compatibility_source text,
  fertilizer_compatibility jsonb NOT NULL DEFAULT '[]'::jsonb,
  sort_order integer NOT NULL DEFAULT 1000,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shortages_seeds_pkey PRIMARY KEY (id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username character varying UNIQUE,
  email character varying NOT NULL UNIQUE,
  password_hash character varying,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['admin'::character varying, 'technician'::character varying, 'jo'::character varying, 'encoder'::character varying, 'farmer'::character varying, 'lgu'::character varying, 'brgychair'::character varying]::text[])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  first_name text,
  last_name text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);