export type FieldCategory = "fertilizer" | "seed";
export type FieldUnit = "bags" | "kg" | "liters";

export type RequestFieldKey = `requested_${string}`;
export type AllocationFieldKey = `${string}`;

export interface ShortageFieldMap {
  label: string;
  category: FieldCategory;
  unit: FieldUnit;
  requestField: RequestFieldKey;
  allocationField: AllocationFieldKey;
  shortageId: string;
}

// Explicit fertilizer field mapping (no runtime inference)
export const FERTILIZER_FIELD_MAPS: ReadonlyArray<ShortageFieldMap> = [
  {
    label: "Urea (46-0-0)",
    category: "fertilizer",
    unit: "bags",
    requestField: "requested_urea_bags",
    allocationField: "urea_46_0_0_bags",
    shortageId: "urea",
  },
  {
    label: "Complete (14-14-14)",
    category: "fertilizer",
    unit: "bags",
    requestField: "requested_complete_14_bags",
    allocationField: "complete_14_14_14_bags",
    shortageId: "complete_14",
  },
  {
    label: "16-20-0",
    category: "fertilizer",
    unit: "bags",
    requestField: "requested_ammonium_phosphate_bags",
    allocationField: "np_16_20_0_bags",
    shortageId: "npk_16_20_0",
  },
  {
    label: "Ammonium Sulfate (21-0-0)",
    category: "fertilizer",
    unit: "bags",
    requestField: "requested_ammonium_sulfate_bags",
    allocationField: "ammonium_sulfate_21_0_0_bags",
    shortageId: "ammonium_sulfate",
  },
  {
    label: "Muriate of Potash (0-0-60)",
    category: "fertilizer",
    unit: "bags",
    requestField: "requested_muriate_potash_bags",
    allocationField: "muriate_potash_0_0_60_bags",
    shortageId: "muriate_of_potash",
  },
  {
    label: "Zinc Sulfate",
    category: "fertilizer",
    unit: "bags",
    requestField: "requested_zinc_sulfate_bags",
    allocationField: "zinc_sulfate_bags",
    shortageId: "zinc_sulfate",
  },
  {
    label: "Vermicompost",
    category: "fertilizer",
    unit: "bags",
    requestField: "requested_vermicompost_bags",
    allocationField: "vermicompost_bags",
    shortageId: "vermicompost",
  },
  {
    label: "Chicken Manure",
    category: "fertilizer",
    unit: "bags",
    requestField: "requested_chicken_manure_bags",
    allocationField: "chicken_manure_bags",
    shortageId: "chicken_manure",
  },
  {
    label: "Rice Straw (incorporated)",
    category: "fertilizer",
    unit: "kg",
    requestField: "requested_rice_straw_kg",
    allocationField: "rice_straw_kg",
    shortageId: "rice_straw",
  },
  {
    label: "Carbonized Rice Hull (CRH)",
    category: "fertilizer",
    unit: "bags",
    requestField: "requested_carbonized_rice_hull_bags",
    allocationField: "carbonized_rice_hull_bags",
    shortageId: "carbonized_rice_hull",
  },
  {
    label: "Biofertilizer (Liquid Concentrate)",
    category: "fertilizer",
    unit: "liters",
    requestField: "requested_biofertilizer_liters",
    allocationField: "biofertilizer_liters",
    shortageId: "biofertilizer",
  },
  {
    label: "Nanobiofertilizer",
    category: "fertilizer",
    unit: "liters",
    requestField: "requested_nanobiofertilizer_liters",
    allocationField: "nanobiofertilizer_liters",
    shortageId: "nanobiofertilizer",
  },
  {
    label: "Organic Root Exudate Mix",
    category: "fertilizer",
    unit: "liters",
    requestField: "requested_organic_root_exudate_mix_liters",
    allocationField: "organic_root_exudate_mix_liters",
    shortageId: "organic_root_exudate",
  },
  {
    label: "Azolla microphylla",
    category: "fertilizer",
    unit: "kg",
    requestField: "requested_azolla_microphylla_kg",
    allocationField: "azolla_microphylla_kg",
    shortageId: "azolla",
  },
  {
    label: "Foliar Liquid Fertilizer (NPK)",
    category: "fertilizer",
    unit: "liters",
    requestField: "requested_foliar_liquid_fertilizer_npk_liters",
    allocationField: "foliar_liquid_fertilizer_npk_liters",
    shortageId: "foliar_liquid_npk",
  },
] as const;

// Explicit seed field mapping (all 32 request fields; no runtime inference)
export const SEED_FIELD_MAPS: ReadonlyArray<ShortageFieldMap> = [
  {
    label: "NSIC Rc 160",
    category: "seed",
    unit: "kg",
    requestField: "requested_rice_seeds_nsic_rc160_kg",
    allocationField: "rice_seeds_nsic_rc160_kg",
    shortageId: "nsic_rc_160",
  },
  {
    label: "NSIC Rc 222",
    category: "seed",
    unit: "kg",
    requestField: "requested_rice_seeds_nsic_rc222_kg",
    allocationField: "rice_seeds_nsic_rc222_kg",
    shortageId: "nsic_rc_222",
  },
  {
    label: "Jackpot",
    category: "seed",
    unit: "kg",
    requestField: "requested_jackpot_kg",
    allocationField: "jackpot_kg",
    shortageId: "jackpot",
  },
  {
    label: "US88",
    category: "seed",
    unit: "kg",
    requestField: "requested_us88_kg",
    allocationField: "us88_kg",
    shortageId: "us88",
  },
  {
    label: "TH82",
    category: "seed",
    unit: "kg",
    requestField: "requested_th82_kg",
    allocationField: "th82_kg",
    shortageId: "th82",
  },
  {
    label: "RH9000",
    category: "seed",
    unit: "kg",
    requestField: "requested_rh9000_kg",
    allocationField: "rh9000_kg",
    shortageId: "rh9000",
  },
  {
    label: "Lumping143",
    category: "seed",
    unit: "kg",
    requestField: "requested_lumping143_kg",
    allocationField: "lumping143_kg",
    shortageId: "lumping_143",
  },
  {
    label: "LP296",
    category: "seed",
    unit: "kg",
    requestField: "requested_lp296_kg",
    allocationField: "lp296_kg",
    shortageId: "lp296",
  },
  {
    label: "Mestiso 1 (M1)",
    category: "seed",
    unit: "kg",
    requestField: "requested_mestiso_1_kg",
    allocationField: "mestiso_1_kg",
    shortageId: "mestiso_1",
  },
  {
    label: "Mestiso 20 (M20)",
    category: "seed",
    unit: "kg",
    requestField: "requested_mestiso_20_kg",
    allocationField: "mestiso_20_kg",
    shortageId: "mestiso_20",
  },
  {
    label: "Mestiso 29",
    category: "seed",
    unit: "kg",
    requestField: "requested_mestiso_29_kg",
    allocationField: "mestiso_29_kg",
    shortageId: "mestiso_29",
  },
  {
    label: "Mestiso 55",
    category: "seed",
    unit: "kg",
    requestField: "requested_mestiso_55_kg",
    allocationField: "mestiso_55_kg",
    shortageId: "mestiso_55",
  },
  {
    label: "Mestiso 73",
    category: "seed",
    unit: "kg",
    requestField: "requested_mestiso_73_kg",
    allocationField: "mestiso_73_kg",
    shortageId: "mestiso_73",
  },
  {
    label: "Mestiso 99",
    category: "seed",
    unit: "kg",
    requestField: "requested_mestiso_99_kg",
    allocationField: "mestiso_99_kg",
    shortageId: "mestiso_99",
  },
  {
    label: "Mestiso 103",
    category: "seed",
    unit: "kg",
    requestField: "requested_mestiso_103_kg",
    allocationField: "mestiso_103_kg",
    shortageId: "mestiso_103",
  },
  {
    label: "NSIC Rc 402",
    category: "seed",
    unit: "kg",
    requestField: "requested_nsic_rc402_kg",
    allocationField: "nsic_rc402_kg",
    shortageId: "nsic_rc_402",
  },
  {
    label: "NSIC Rc 480",
    category: "seed",
    unit: "kg",
    requestField: "requested_nsic_rc480_kg",
    allocationField: "nsic_rc480_kg",
    shortageId: "nsic_rc_480",
  },
  {
    label: "NSIC Rc 216",
    category: "seed",
    unit: "kg",
    requestField: "requested_nsic_rc216_kg",
    allocationField: "nsic_rc216_kg",
    shortageId: "nsic_rc_216",
  },
  {
    label: "NSIC Rc 218",
    category: "seed",
    unit: "kg",
    requestField: "requested_nsic_rc218_kg",
    allocationField: "nsic_rc218_kg",
    shortageId: "nsic_rc_218",
  },
  {
    label: "NSIC Rc 506",
    category: "seed",
    unit: "kg",
    requestField: "requested_nsic_rc506_kg",
    allocationField: "nsic_rc506_kg",
    shortageId: "nsic_rc_506",
  },
  {
    label: "NSIC Rc 508",
    category: "seed",
    unit: "kg",
    requestField: "requested_nsic_rc508_kg",
    allocationField: "nsic_rc508_kg",
    shortageId: "nsic_rc_508",
  },
  {
    label: "NSIC Rc 512",
    category: "seed",
    unit: "kg",
    requestField: "requested_nsic_rc512_kg",
    allocationField: "nsic_rc512_kg",
    shortageId: "nsic_rc_512",
  },
  {
    label: "NSIC Rc 534",
    category: "seed",
    unit: "kg",
    requestField: "requested_nsic_rc534_kg",
    allocationField: "nsic_rc534_kg",
    shortageId: "nsic_rc_534",
  },
  {
    label: "Tubigan 28",
    category: "seed",
    unit: "kg",
    requestField: "requested_tubigan_28_kg",
    allocationField: "tubigan_28_kg",
    shortageId: "tubigan_28",
  },
  {
    label: "Tubigan 30",
    category: "seed",
    unit: "kg",
    requestField: "requested_tubigan_30_kg",
    allocationField: "tubigan_30_kg",
    shortageId: "tubigan_30",
  },
  {
    label: "Tubigan 22",
    category: "seed",
    unit: "kg",
    requestField: "requested_tubigan_22_kg",
    allocationField: "tubigan_22_kg",
    shortageId: "tubigan_22",
  },
  {
    label: "Sahod Ulan 2",
    category: "seed",
    unit: "kg",
    requestField: "requested_sahod_ulan_2_kg",
    allocationField: "sahod_ulan_2_kg",
    shortageId: "sahod_ulan_2",
  },
  {
    label: "Sahod Ulan 10",
    category: "seed",
    unit: "kg",
    requestField: "requested_sahod_ulan_10_kg",
    allocationField: "sahod_ulan_10_kg",
    shortageId: "sahod_ulan_10",
  },
  {
    label: "Salinas 6",
    category: "seed",
    unit: "kg",
    requestField: "requested_salinas_6_kg",
    allocationField: "salinas_6_kg",
    shortageId: "salinas_6",
  },
  {
    label: "Salinas 7",
    category: "seed",
    unit: "kg",
    requestField: "requested_salinas_7_kg",
    allocationField: "salinas_7_kg",
    shortageId: "salinas_7",
  },
  {
    label: "Salinas 8",
    category: "seed",
    unit: "kg",
    requestField: "requested_salinas_8_kg",
    allocationField: "salinas_8_kg",
    shortageId: "salinas_8",
  },
  {
    label: "Malagkit 5",
    category: "seed",
    unit: "kg",
    requestField: "requested_malagkit_5_kg",
    allocationField: "malagkit_5_kg",
    shortageId: "malagkit_5",
  },
] as const;

export const ALL_SHORTAGE_FIELD_MAPS: ReadonlyArray<ShortageFieldMap> = [
  ...FERTILIZER_FIELD_MAPS,
  ...SEED_FIELD_MAPS,
];

export const SHORTAGE_FIELD_MAP_BY_REQUEST_FIELD: Readonly<
  Record<string, ShortageFieldMap>
> = ALL_SHORTAGE_FIELD_MAPS.reduce<Record<string, ShortageFieldMap>>(
  (acc, mapItem) => {
    acc[mapItem.requestField] = mapItem;
    return acc;
  },
  {},
);
