-- Add all missing columns from Philrice catalog to regional_allocations and farmer_requests
-- This ensures that the Admin can allocate and the JO can request all Philrice-listed subsidies.

-- 1. Update regional_allocations (Admin side)
ALTER TABLE public.regional_allocations
  ADD COLUMN IF NOT EXISTS zinc_sulfate_bags INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vermicompost_bags INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chicken_manure_bags INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rice_straw_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carbonized_rice_hull_bags INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS biofertilizer_liters DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nanobiofertilizer_liters DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS organic_root_exudate_mix_liters DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS azolla_microphylla_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS foliar_liquid_fertilizer_npk_liters DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS jackpot_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS us88_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS th82_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rh9000_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lumping143_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lp296_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mestiso_1_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mestiso_20_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mestiso_29_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mestiso_55_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mestiso_73_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mestiso_99_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mestiso_103_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nsic_rc402_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nsic_rc480_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nsic_rc216_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nsic_rc218_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nsic_rc506_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nsic_rc508_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nsic_rc512_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS nsic_rc534_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tubigan_28_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tubigan_30_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tubigan_22_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sahod_ulan_2_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sahod_ulan_10_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS salinas_6_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS salinas_7_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS salinas_8_kg DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS malagkit_5_kg DECIMAL(10,2) DEFAULT 0;

-- 2. Update farmer_requests (JO side)
-- Note: Some of these might already exist from previous migrations, but ADD COLUMN IF NOT EXISTS is safe.
ALTER TABLE public.farmer_requests
  ADD COLUMN IF NOT EXISTS requested_jackpot_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_us88_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_th82_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_rh9000_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_lumping143_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_lp296_kg numeric(10,2) DEFAULT 0;
