-- Add missing requested item columns so JO Add Farmer Request can save all
-- allocation items (fertilizers and seeds) end-to-end.

ALTER TABLE public.farmer_requests
  ADD COLUMN IF NOT EXISTS requested_zinc_sulfate_bags numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_vermicompost_bags numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_chicken_manure_bags numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_rice_straw_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_carbonized_rice_hull_bags numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_biofertilizer_liters numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_nanobiofertilizer_liters numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_organic_root_exudate_mix_liters numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_azolla_microphylla_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_foliar_liquid_fertilizer_npk_liters numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_rice_seeds_nsic_rc160_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_rice_seeds_nsic_rc222_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_mestiso_1_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_mestiso_20_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_mestiso_29_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_mestiso_55_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_mestiso_73_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_mestiso_99_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_mestiso_103_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_nsic_rc402_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_nsic_rc480_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_nsic_rc216_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_nsic_rc218_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_nsic_rc506_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_nsic_rc508_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_nsic_rc512_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_nsic_rc534_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_tubigan_28_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_tubigan_30_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_tubigan_22_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_sahod_ulan_2_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_sahod_ulan_10_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_salinas_6_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_salinas_7_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_salinas_8_kg numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS requested_malagkit_5_kg numeric(10,2) DEFAULT 0;
