create table public.farmer_requests (
  id serial not null,
  season character varying(50) not null,
  request_date date null default CURRENT_DATE,
  farmer_id integer null,
  farmer_name character varying(255) not null,
  barangay character varying(100) null,
  farm_area_ha numeric(10, 2) not null,
  crop_type character varying(100) null,
  ownership_type character varying(50) null,
  num_parcels integer null default 1,
  fertilizer_requested boolean null default false,
  seeds_requested boolean null default false,
  request_notes text null,
  priority_score integer null default 0,
  priority_rank integer null,
  assigned_fertilizer_type character varying(100) null,
  assigned_fertilizer_bags integer null,
  assigned_seed_type character varying(100) null,
  assigned_seed_kg numeric(10, 2) null,
  fertilizer_accepted boolean null,
  seeds_accepted boolean null,
  rejection_reason text null,
  status character varying(50) null default 'pending'::character varying,
  created_by integer null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  requested_urea_bags numeric(10, 2) null default 0,
  requested_complete_14_bags numeric(10, 2) null default 0,
  requested_complete_16_bags numeric(10, 2) null default 0,
  requested_ammonium_sulfate_bags numeric(10, 2) null default 0,
  requested_ammonium_phosphate_bags numeric(10, 2) null default 0,
  requested_muriate_potash_bags numeric(10, 2) null default 0,
  requested_jackpot_kg numeric(10, 2) null default 0,
  requested_us88_kg numeric(10, 2) null default 0,
  requested_th82_kg numeric(10, 2) null default 0,
  requested_rh9000_kg numeric(10, 2) null default 0,
  requested_lumping143_kg numeric(10, 2) null default 0,
  requested_lp296_kg numeric(10, 2) null default 0,
  allocation_id integer null,
  requested_zinc_sulfate_bags numeric(10, 2) null default 0,
  requested_vermicompost_bags numeric(10, 2) null default 0,
  requested_chicken_manure_bags numeric(10, 2) null default 0,
  requested_rice_straw_kg numeric(10, 2) null default 0,
  requested_carbonized_rice_hull_bags numeric(10, 2) null default 0,
  requested_biofertilizer_liters numeric(10, 2) null default 0,
  requested_nanobiofertilizer_liters numeric(10, 2) null default 0,
  requested_organic_root_exudate_mix_liters numeric(10, 2) null default 0,
  requested_azolla_microphylla_kg numeric(10, 2) null default 0,
  requested_foliar_liquid_fertilizer_npk_liters numeric(10, 2) null default 0,
  requested_rice_seeds_nsic_rc160_kg numeric(10, 2) null default 0,
  requested_rice_seeds_nsic_rc222_kg numeric(10, 2) null default 0,
  requested_mestiso_1_kg numeric(10, 2) null default 0,
  requested_mestiso_20_kg numeric(10, 2) null default 0,
  requested_mestiso_29_kg numeric(10, 2) null default 0,
  requested_mestiso_55_kg numeric(10, 2) null default 0,
  requested_mestiso_73_kg numeric(10, 2) null default 0,
  requested_mestiso_99_kg numeric(10, 2) null default 0,
  requested_mestiso_103_kg numeric(10, 2) null default 0,
  requested_nsic_rc402_kg numeric(10, 2) null default 0,
  requested_nsic_rc480_kg numeric(10, 2) null default 0,
  requested_nsic_rc216_kg numeric(10, 2) null default 0,
  requested_nsic_rc218_kg numeric(10, 2) null default 0,
  requested_nsic_rc506_kg numeric(10, 2) null default 0,
  requested_nsic_rc508_kg numeric(10, 2) null default 0,
  requested_nsic_rc512_kg numeric(10, 2) null default 0,
  requested_nsic_rc534_kg numeric(10, 2) null default 0,
  requested_tubigan_28_kg numeric(10, 2) null default 0,
  requested_tubigan_30_kg numeric(10, 2) null default 0,
  requested_tubigan_22_kg numeric(10, 2) null default 0,
  requested_sahod_ulan_2_kg numeric(10, 2) null default 0,
  requested_sahod_ulan_10_kg numeric(10, 2) null default 0,
  requested_salinas_6_kg numeric(10, 2) null default 0,
  requested_salinas_7_kg numeric(10, 2) null default 0,
  requested_salinas_8_kg numeric(10, 2) null default 0,
  requested_malagkit_5_kg numeric(10, 2) null default 0,
  requested_corn_seeds_hybrid_kg numeric null default 0,
  requested_corn_seeds_opm_kg numeric null default 0,
  requested_vegetable_seeds_kg numeric null default 0,
  requested_np_16_20_0_bags numeric null default 0,
  requested_rice_seeds_nsic_rc440_kg numeric null default 0,
  constraint farmer_requests_pkey primary key (id),
  constraint farmer_requests_farmer_id_fkey foreign KEY (farmer_id) references rsbsa_submission (id) on delete set null,
  constraint fk_farmer_requests_allocation foreign KEY (allocation_id) references regional_allocations (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_requests_farmer on public.farmer_requests using btree (farmer_id) TABLESPACE pg_default;

create index IF not exists idx_requests_priority on public.farmer_requests using btree (priority_score desc) TABLESPACE pg_default;

create index IF not exists idx_requests_season on public.farmer_requests using btree (season) TABLESPACE pg_default;

create index IF not exists idx_requests_status on public.farmer_requests using btree (status) TABLESPACE pg_default;

create index IF not exists idx_farmer_requests_allocation_id on public.farmer_requests using btree (allocation_id) TABLESPACE pg_default;