-- ============================================================================
-- INSERT 50 SAMPLE FARMERS - SAFE VERSION
-- ============================================================================
-- This script safely inserts 50 farmers WITHOUT causing ID conflicts
-- It skips farmers that already exist based on name matching
-- IDs are auto-generated by the database
-- ============================================================================

-- Step 1: Create a temporary table for our sample data
CREATE TEMP TABLE temp_sample_farmers (
    last_name VARCHAR(255),
    first_name VARCHAR(255),
    middle_name VARCHAR(255),
    ext_name VARCHAR(255),
    gender VARCHAR(10),
    birthdate DATE,
    age INTEGER,
    barangay VARCHAR(255),
    municipality VARCHAR(255),
    farm_location VARCHAR(50),
    parcel_area NUMERIC(10,2),
    main_livelihood VARCHAR(100),
    ownership_registered BOOLEAN,
    ownership_tenant BOOLEAN,
    ownership_lessee BOOLEAN
);

-- Step 2: Insert sample data into temp table
INSERT INTO temp_sample_farmers VALUES
-- Registered Owners from various barangays (1-10)
('Dela Cruz', 'Juan', 'Santos', NULL, 'Male', '1975-03-15', 48, 'Aurora-Del Pilar', 'Dumangas', 'Aurora-Del Pilar', 2.5, 'farmer', TRUE, FALSE, FALSE),
('Reyes', 'Maria', 'Garcia', NULL, 'Female', '1982-07-22', 41, 'Bacay', 'Dumangas', 'Bacay', 1.8, 'farmer', TRUE, FALSE, FALSE),
('Santos', 'Roberto', 'Mendoza', NULL, 'Male', '1968-11-08', 55, 'Balabag', 'Dumangas', 'Balabag', 3.2, 'farmer', TRUE, FALSE, FALSE),
('Garcia', 'Elena', 'Flores', NULL, 'Female', '1979-05-30', 44, 'Bantud', 'Dumangas', 'Bantud', 2.1, 'farmer', TRUE, FALSE, FALSE),
('Hernandez', 'Pedro', 'Aquino', NULL, 'Male', '1970-09-14', 53, 'Baras', 'Dumangas', 'Baras', 4.5, 'farmer', TRUE, FALSE, FALSE),
('Martinez', 'Rosa', 'Bautista', NULL, 'Female', '1985-01-18', 38, 'Barasan', 'Dumangas', 'Barasan', 1.5, 'farmer', TRUE, FALSE, FALSE),
('Gonzales', 'Antonio', 'Cruz', NULL, 'Male', '1973-12-25', 50, 'Bolilao', 'Dumangas', 'Bolilao', 2.8, 'farmer', TRUE, FALSE, FALSE),
('Torres', 'Carmen', 'Ramos', NULL, 'Female', '1988-04-02', 35, 'Calao', 'Dumangas', 'Calao', 1.2, 'farmer', TRUE, FALSE, FALSE),
('Fernandez', 'Ricardo', 'Villanueva', NULL, 'Male', '1965-08-19', 58, 'Cali', 'Dumangas', 'Cali', 3.7, 'farmer', TRUE, FALSE, FALSE),
('Lopez', 'Lourdes', 'Santiago', NULL, 'Female', '1980-06-11', 43, 'Cansilayan', 'Dumangas', 'Cansilayan', 2.3, 'farmer', TRUE, FALSE, FALSE),

-- Mix of Registered Owners and Tenants (11-20)
('Castillo', 'Manuel', 'Rivera', NULL, 'Male', '1977-02-28', 46, 'Capaliz', 'Dumangas', 'Capaliz', 1.9, 'farmer', TRUE, FALSE, FALSE),
('Ramirez', 'Teresa', 'Morales', NULL, 'Female', '1983-10-07', 40, 'Cayos', 'Dumangas', 'Cayos', 2.6, 'farmer', FALSE, TRUE, FALSE),
('Morales', 'Jose', 'Diaz', NULL, 'Male', '1972-07-16', 51, 'Compayan', 'Dumangas', 'Compayan', 1.4, 'farmer', FALSE, TRUE, FALSE),
('Velasco', 'Gloria', 'Gomez', NULL, 'Female', '1986-03-09', 37, 'Dacutan', 'Dumangas', 'Dacutan', 3.1, 'farmer', TRUE, FALSE, FALSE),
('Mendoza', 'Alfredo', 'Perez', NULL, 'Male', '1969-11-23', 54, 'Ermita', 'Dumangas', 'Ermita', 2.4, 'farmer', FALSE, TRUE, FALSE),
('Cruz', 'Violeta', 'Torres', NULL, 'Female', '1981-05-14', 42, 'Ilaya 1st', 'Dumangas', 'Ilaya 1st', 1.7, 'farmer', TRUE, FALSE, FALSE),
('Bautista', 'Fernando', 'Lopez', NULL, 'Male', '1974-09-01', 49, 'Ilaya 2nd', 'Dumangas', 'Ilaya 2nd', 3.5, 'farmer', FALSE, TRUE, FALSE),
('Flores', 'Angelina', 'Castro', NULL, 'Female', '1987-01-27', 36, 'Ilaya 3rd', 'Dumangas', 'Ilaya 3rd', 2.0, 'farmer', TRUE, FALSE, FALSE),
('Aquino', 'Eduardo', 'Navarro', NULL, 'Male', '1966-08-12', 57, 'Jardin', 'Dumangas', 'Jardin', 4.2, 'farmer', TRUE, FALSE, FALSE),
('Ramos', 'Cristina', 'Fernandez', NULL, 'Female', '1984-12-05', 39, 'Lacturan', 'Dumangas', 'Lacturan', 1.6, 'farmer', FALSE, TRUE, FALSE),

-- More variety including lessees (21-30)
('Villanueva', 'Miguel', 'Gonzales', NULL, 'Male', '1976-04-20', 47, 'Lopez Jaena - Rizal', 'Dumangas', 'Lopez Jaena - Rizal', 2.9, 'farmer', FALSE, FALSE, TRUE),
('Santiago', 'Rosario', 'Martinez', NULL, 'Female', '1989-06-18', 34, 'Managuit', 'Dumangas', 'Managuit', 1.3, 'farmer', TRUE, FALSE, FALSE),
('Rivera', 'Benjamin', 'Hernandez', NULL, 'Male', '1971-10-31', 52, 'Maquina', 'Dumangas', 'Maquina', 3.8, 'farmer', FALSE, FALSE, TRUE),
('Diaz', 'Luisa', 'Reyes', NULL, 'Female', '1985-02-13', 38, 'Nanding Lopez', 'Dumangas', 'Nanding Lopez', 2.2, 'farmer', TRUE, FALSE, FALSE),
('Gomez', 'Carlos', 'Santos', NULL, 'Male', '1968-07-08', 55, 'Pagdugue', 'Dumangas', 'Pagdugue', 1.9, 'farmer', FALSE, TRUE, FALSE),
('Perez', 'Estrella', 'Dela Cruz', NULL, 'Female', '1982-11-26', 41, 'Paloc Bigque', 'Dumangas', 'Paloc Bigque', 3.4, 'farmer', TRUE, FALSE, FALSE),
('Castro', 'Ramon', 'Garcia', NULL, 'Male', '1973-05-19', 50, 'Paloc Sool', 'Dumangas', 'Paloc Sool', 2.7, 'farmer', FALSE, FALSE, TRUE),
('Navarro', 'Norma', 'Castillo', NULL, 'Female', '1988-09-03', 35, 'Patlad', 'Dumangas', 'Patlad', 1.5, 'farmer', TRUE, FALSE, FALSE),
('Torres', 'Alberto', 'Ramirez', NULL, 'Male', '1967-01-24', 56, 'Pd Monfort North', 'Dumangas', 'Pd Monfort North', 4.1, 'farmer', TRUE, FALSE, FALSE),
('Lopez', 'Beatriz', 'Morales', NULL, 'Female', '1984-03-17', 39, 'Pd Monfort South', 'Dumangas', 'Pd Monfort South', 2.5, 'farmer', FALSE, TRUE, FALSE),

-- Younger farmers with smaller farms (31-40)
('Gonzales', 'Jerome', 'Velasco', NULL, 'Male', '1992-08-09', 31, 'Pulao', 'Dumangas', 'Pulao', 1.2, 'farmer', TRUE, FALSE, FALSE),
('Martinez', 'Jennifer', 'Mendoza', NULL, 'Female', '1990-12-21', 33, 'Rosario', 'Dumangas', 'Rosario', 1.8, 'farmer', FALSE, TRUE, FALSE),
('Hernandez', 'Ryan', 'Cruz', NULL, 'Male', '1991-04-15', 32, 'Sapao', 'Dumangas', 'Sapao', 2.1, 'farmer', TRUE, FALSE, FALSE),
('Reyes', 'Michelle', 'Bautista', NULL, 'Female', '1993-07-28', 30, 'Sulangan', 'Dumangas', 'Sulangan', 1.4, 'farmer', FALSE, FALSE, TRUE),
('Santos', 'Mark', 'Flores', NULL, 'Male', '1989-10-11', 34, 'Tabucan', 'Dumangas', 'Tabucan', 2.6, 'farmer', TRUE, FALSE, FALSE),
('Garcia', 'Anna', 'Aquino', NULL, 'Female', '1994-02-05', 29, 'Talusan', 'Dumangas', 'Talusan', 1.6, 'farmer', FALSE, TRUE, FALSE),
('Dela Cruz', 'Joseph', 'Ramos', NULL, 'Male', '1990-06-19', 33, 'Tambobo', 'Dumangas', 'Tambobo', 2.9, 'farmer', TRUE, FALSE, FALSE),
('Mendoza', 'Maria Fe', 'Villanueva', NULL, 'Female', '1992-09-23', 31, 'Tamboilan', 'Dumangas', 'Tamboilan', 1.7, 'farmer', FALSE, FALSE, TRUE),
('Cruz', 'Christian', 'Santiago', NULL, 'Male', '1988-11-07', 35, 'Victorias', 'Dumangas', 'Victorias', 3.2, 'farmer', TRUE, FALSE, FALSE),
('Bautista', 'Sheryl', 'Rivera', NULL, 'Female', '1991-03-14', 32, 'Aurora-Del Pilar', 'Dumangas', 'Aurora-Del Pilar', 2.0, 'farmer', FALSE, TRUE, FALSE),

-- Older experienced farmers with larger farms (41-50)
('Flores', 'Rodrigo', 'Diaz', NULL, 'Male', '1960-05-10', 63, 'Bacay', 'Dumangas', 'Bacay', 5.2, 'farmer', TRUE, FALSE, FALSE),
('Aquino', 'Teresita', 'Gomez', NULL, 'Female', '1963-09-22', 60, 'Bacong', 'Dumangas', 'Bacong', 3.8, 'farmer', TRUE, FALSE, FALSE),
('Ramos', 'Francisco', 'Perez', NULL, 'Male', '1962-01-16', 61, 'Balud', 'Dumangas', 'Balud', 4.6, 'farmer', TRUE, FALSE, FALSE),
('Villanueva', 'Perpetua', 'Castro', NULL, 'Female', '1964-07-29', 59, 'Bantud Fabrica', 'Dumangas', 'Bantud Fabrica', 3.5, 'farmer', FALSE, TRUE, FALSE),
('Santiago', 'Ernesto', 'Navarro', NULL, 'Male', '1961-11-03', 62, 'Basa-Mabini Bonifacio', 'Dumangas', 'Basa-Mabini Bonifacio', 4.9, 'farmer', TRUE, FALSE, FALSE),
('Rivera', 'Felicitas', 'Torres', NULL, 'Female', '1965-03-25', 58, 'Buenaflor Embarkadero', 'Dumangas', 'Buenaflor Embarkadero', 2.8, 'farmer', FALSE, FALSE, TRUE),
('Diaz', 'Marcelo', 'Lopez', NULL, 'Male', '1959-08-18', 64, 'Burgos-Regidor', 'Dumangas', 'Burgos-Regidor', 5.5, 'farmer', TRUE, FALSE, FALSE),
('Gomez', 'Amparo', 'Gonzales', NULL, 'Female', '1966-12-11', 57, 'Calao', 'Dumangas', 'Calao', 3.1, 'farmer', FALSE, TRUE, FALSE),
('Perez', 'Emilio', 'Martinez', NULL, 'Male', '1958-04-07', 65, 'Cali', 'Dumangas', 'Cali', 6.2, 'farmer', TRUE, FALSE, FALSE),
('Castro', 'Remedios', 'Hernandez', NULL, 'Female', '1967-10-28', 56, 'Cansilayan', 'Dumangas', 'Cansilayan', 4.3, 'farmer', TRUE, FALSE, FALSE);

-- Step 3: Insert into rsbsa_submission ONLY if farmer doesn't already exist
INSERT INTO rsbsa_submission (
    "LAST NAME", 
    "FIRST NAME", 
    "MIDDLE NAME", 
    "EXT NAME",
    "GENDER", 
    "BIRTHDATE",
    age,
    "BARANGAY", 
    "MUNICIPALITY",
    "FARM LOCATION",
    "PARCEL AREA",
    "TOTAL FARM AREA",
    "MAIN LIVELIHOOD",
    "OWNERSHIP_TYPE_REGISTERED_OWNER",
    "OWNERSHIP_TYPE_TENANT",
    "OWNERSHIP_TYPE_LESSEE",
    status
)
SELECT 
    t.last_name,
    t.first_name,
    t.middle_name,
    t.ext_name,
    t.gender,
    t.birthdate,
    t.age,
    t.barangay,
    t.municipality,
    t.farm_location,
    t.parcel_area,
    t.parcel_area,
    t.main_livelihood,
    t.ownership_registered,
    t.ownership_tenant,
    t.ownership_lessee,
    'Submitted'
FROM temp_sample_farmers t
WHERE NOT EXISTS (
    SELECT 1 
    FROM rsbsa_submission r 
    WHERE r."FIRST NAME" = t.first_name 
    AND r."LAST NAME" = t.last_name
    AND r."BARANGAY" = t.barangay
);

-- Step 4: Create temporary mapping table for parcel insertion
CREATE TEMP TABLE temp_farmer_ids AS
SELECT 
    r.id as submission_id,
    r."FIRST NAME" as first_name,
    r."LAST NAME" as last_name,
    r."BARANGAY" as barangay
FROM rsbsa_submission r
INNER JOIN temp_sample_farmers t 
    ON r."FIRST NAME" = t.first_name 
    AND r."LAST NAME" = t.last_name
    AND r."BARANGAY" = t.barangay;

-- Step 5: Insert farm parcels using the mapping table
-- Parcel 1 for each farmer
INSERT INTO rsbsa_farm_parcels (
    submission_id,
    parcel_number,
    farm_location_barangay,
    farm_location_municipality,
    total_farm_area_ha,
    within_ancestral_domain,
    ownership_document_no,
    agrarian_reform_beneficiary,
    ownership_type_registered_owner,
    ownership_type_tenant,
    ownership_type_lessee,
    tenant_land_owner_name,
    lessee_land_owner_name
)
SELECT submission_id, '1', 'Aurora-Del Pilar', 'Dumangas', 2.5, 'No', 'TD-2015-0123', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Juan' AND last_name = 'Dela Cruz'
UNION ALL SELECT submission_id, '1', 'Bacay', 'Dumangas', 1.8, 'No', 'TD-2018-0456', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Maria' AND last_name = 'Reyes'
UNION ALL SELECT submission_id, '1', 'Balabag', 'Dumangas', 2.0, 'No', 'TD-2012-0789', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Roberto' AND last_name = 'Santos'
UNION ALL SELECT submission_id, '2', 'Balabag', 'Dumangas', 1.2, 'No', 'TD-2016-0790', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Roberto' AND last_name = 'Santos'
UNION ALL SELECT submission_id, '1', 'Bantud', 'Dumangas', 2.1, 'No', 'TD-2017-1234', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Elena' AND last_name = 'Garcia'
UNION ALL SELECT submission_id, '1', 'Baras', 'Dumangas', 3.0, 'No', 'TD-2010-5678', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Pedro' AND last_name = 'Hernandez'
UNION ALL SELECT submission_id, '2', 'Baras', 'Dumangas', 1.5, 'No', 'TD-2014-5679', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Pedro' AND last_name = 'Hernandez'
UNION ALL SELECT submission_id, '1', 'Barasan', 'Dumangas', 1.5, 'No', 'TD-2019-9012', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Rosa' AND last_name = 'Martinez'
UNION ALL SELECT submission_id, '1', 'Bolilao', 'Dumangas', 2.8, 'No', 'TD-2013-3456', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Antonio' AND last_name = 'Gonzales'
UNION ALL SELECT submission_id, '1', 'Calao', 'Dumangas', 1.2, 'No', 'TD-2020-7890', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Carmen' AND last_name = 'Torres'
UNION ALL SELECT submission_id, '1', 'Cali', 'Dumangas', 2.5, 'No', 'TD-2008-1122', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Ricardo' AND last_name = 'Fernandez'
UNION ALL SELECT submission_id, '2', 'Cali', 'Dumangas', 1.2, 'No', 'TD-2011-1123', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Ricardo' AND last_name = 'Fernandez'
UNION ALL SELECT submission_id, '1', 'Cansilayan', 'Dumangas', 2.3, 'No', 'TD-2016-3344', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Lourdes' AND last_name = 'Lopez'
UNION ALL SELECT submission_id, '1', 'Capaliz', 'Dumangas', 1.9, 'No', 'TD-2015-5566', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Manuel' AND last_name = 'Castillo'
UNION ALL SELECT submission_id, '1', 'Cayos', 'Dumangas', 2.6, 'No', NULL, 'Yes', FALSE, TRUE, FALSE, 'Dela Cruz, Juan', NULL FROM temp_farmer_ids WHERE first_name = 'Teresa' AND last_name = 'Ramirez'
UNION ALL SELECT submission_id, '1', 'Compayan', 'Dumangas', 1.4, 'No', NULL, 'No', FALSE, TRUE, FALSE, 'Santos, Roberto', NULL FROM temp_farmer_ids WHERE first_name = 'Jose' AND last_name = 'Morales'
UNION ALL SELECT submission_id, '1', 'Dacutan', 'Dumangas', 3.1, 'No', 'TD-2019-7788', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Gloria' AND last_name = 'Velasco'
UNION ALL SELECT submission_id, '1', 'Ermita', 'Dumangas', 2.4, 'No', NULL, 'Yes', FALSE, TRUE, FALSE, 'Hernandez, Pedro', NULL FROM temp_farmer_ids WHERE first_name = 'Alfredo' AND last_name = 'Mendoza'
UNION ALL SELECT submission_id, '1', 'Ilaya 1st', 'Dumangas', 1.7, 'No', 'TD-2017-9900', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Violeta' AND last_name = 'Cruz'
UNION ALL SELECT submission_id, '1', 'Ilaya 2nd', 'Dumangas', 3.5, 'No', NULL, 'Yes', FALSE, TRUE, FALSE, 'Aquino, Eduardo', NULL FROM temp_farmer_ids WHERE first_name = 'Fernando' AND last_name = 'Bautista'
UNION ALL SELECT submission_id, '1', 'Ilaya 3rd', 'Dumangas', 2.0, 'No', 'TD-2020-1122', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Angelina' AND last_name = 'Flores'
UNION ALL SELECT submission_id, '1', 'Jardin', 'Dumangas', 4.2, 'No', 'TD-2009-3344', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Eduardo' AND last_name = 'Aquino'
UNION ALL SELECT submission_id, '1', 'Lacturan', 'Dumangas', 1.6, 'No', NULL, 'No', FALSE, TRUE, FALSE, 'Torres, Alberto', NULL FROM temp_farmer_ids WHERE first_name = 'Cristina' AND last_name = 'Ramos'
UNION ALL SELECT submission_id, '1', 'Lopez Jaena - Rizal', 'Dumangas', 2.9, 'No', NULL, 'No', FALSE, FALSE, TRUE, NULL, 'Gonzales, Antonio' FROM temp_farmer_ids WHERE first_name = 'Miguel' AND last_name = 'Villanueva'
UNION ALL SELECT submission_id, '1', 'Managuit', 'Dumangas', 1.3, 'No', 'TD-2021-5566', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Rosario' AND last_name = 'Santiago'
UNION ALL SELECT submission_id, '1', 'Maquina', 'Dumangas', 3.8, 'No', NULL, 'Yes', FALSE, FALSE, TRUE, NULL, 'Fernandez, Ricardo' FROM temp_farmer_ids WHERE first_name = 'Benjamin' AND last_name = 'Rivera'
UNION ALL SELECT submission_id, '1', 'Nanding Lopez', 'Dumangas', 2.2, 'No', 'TD-2018-7788', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Luisa' AND last_name = 'Diaz'
UNION ALL SELECT submission_id, '1', 'Pagdugue', 'Dumangas', 1.9, 'No', NULL, 'No', FALSE, TRUE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Carlos' AND last_name = 'Gomez'
UNION ALL SELECT submission_id, '1', 'Paloc Bigque', 'Dumangas', 3.4, 'No', 'TD-2016-9900', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Estrella' AND last_name = 'Perez'
UNION ALL SELECT submission_id, '1', 'Paloc Sool', 'Dumangas', 2.7, 'No', NULL, 'No', FALSE, FALSE, TRUE, NULL, 'Castillo, Manuel' FROM temp_farmer_ids WHERE first_name = 'Ramon' AND last_name = 'Castro'
UNION ALL SELECT submission_id, '1', 'Patlad', 'Dumangas', 1.5, 'No', 'TD-2020-1122', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Norma' AND last_name = 'Navarro'
UNION ALL SELECT submission_id, '1', 'Pd Monfort North', 'Dumangas', 4.1, 'No', 'TD-2010-3344', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Alberto' AND last_name = 'Torres'
UNION ALL SELECT submission_id, '1', 'Pd Monfort South', 'Dumangas', 2.5, 'No', NULL, 'No', FALSE, TRUE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Beatriz' AND last_name = 'Lopez'
UNION ALL SELECT submission_id, '1', 'Pulao', 'Dumangas', 1.2, 'No', 'TD-2021-5566', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Jerome' AND last_name = 'Gonzales'
UNION ALL SELECT submission_id, '1', 'Rosario', 'Dumangas', 1.8, 'No', NULL, 'No', FALSE, TRUE, FALSE, 'Velasco, Gloria', NULL FROM temp_farmer_ids WHERE first_name = 'Jennifer' AND last_name = 'Martinez'
UNION ALL SELECT submission_id, '1', 'Sapao', 'Dumangas', 2.1, 'No', 'TD-2020-7788', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Ryan' AND last_name = 'Hernandez'
UNION ALL SELECT submission_id, '1', 'Sulangan', 'Dumangas', 1.4, 'No', NULL, 'No', FALSE, FALSE, TRUE, NULL, 'Perez, Estrella' FROM temp_farmer_ids WHERE first_name = 'Michelle' AND last_name = 'Reyes'
UNION ALL SELECT submission_id, '1', 'Tabucan', 'Dumangas', 2.6, 'No', 'TD-2019-9900', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Mark' AND last_name = 'Santos'
UNION ALL SELECT submission_id, '1', 'Talusan', 'Dumangas', 1.6, 'No', NULL, 'No', FALSE, TRUE, FALSE, 'Flores, Alberto', NULL FROM temp_farmer_ids WHERE first_name = 'Anna' AND last_name = 'Garcia'
UNION ALL SELECT submission_id, '1', 'Tambobo', 'Dumangas', 2.9, 'No', 'TD-2021-1122', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Joseph' AND last_name = 'Dela Cruz'
UNION ALL SELECT submission_id, '1', 'Tamboilan', 'Dumangas', 1.7, 'No', NULL, 'No', FALSE, FALSE, TRUE, NULL, 'Cruz, Christian' FROM temp_farmer_ids WHERE first_name = 'Maria Fe' AND last_name = 'Mendoza'
UNION ALL SELECT submission_id, '1', 'Victorias', 'Dumangas', 3.2, 'No', 'TD-2020-3344', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Christian' AND last_name = 'Cruz'
UNION ALL SELECT submission_id, '1', 'Aurora-Del Pilar', 'Dumangas', 2.0, 'No', NULL, 'Yes', FALSE, TRUE, FALSE, 'Dela Cruz, Juan', NULL FROM temp_farmer_ids WHERE first_name = 'Sheryl' AND last_name = 'Bautista'
UNION ALL SELECT submission_id, '1', 'Bacay', 'Dumangas', 3.0, 'No', 'TD-2005-5566', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Rodrigo' AND last_name = 'Flores'
UNION ALL SELECT submission_id, '2', 'Bacay', 'Dumangas', 2.2, 'No', 'TD-2007-5567', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Rodrigo' AND last_name = 'Flores'
UNION ALL SELECT submission_id, '1', 'Bacong', 'Dumangas', 2.5, 'No', 'TD-2006-7788', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Teresita' AND last_name = 'Aquino'
UNION ALL SELECT submission_id, '2', 'Bacong', 'Dumangas', 1.3, 'No', 'TD-2008-7789', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Teresita' AND last_name = 'Aquino'
UNION ALL SELECT submission_id, '1', 'Balud', 'Dumangas', 3.0, 'No', 'TD-2007-9900', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Francisco' AND last_name = 'Ramos'
UNION ALL SELECT submission_id, '2', 'Balud', 'Dumangas', 1.6, 'No', 'TD-2009-9901', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Francisco' AND last_name = 'Ramos'
UNION ALL SELECT submission_id, '1', 'Bantud Fabrica', 'Dumangas', 3.5, 'No', NULL, 'Yes', FALSE, TRUE, FALSE, 'Gonzales, Antonio', NULL FROM temp_farmer_ids WHERE first_name = 'Perpetua' AND last_name = 'Villanueva'
UNION ALL SELECT submission_id, '1', 'Basa-Mabini Bonifacio', 'Dumangas', 3.2, 'No', 'TD-2004-1122', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Ernesto' AND last_name = 'Santiago'
UNION ALL SELECT submission_id, '2', 'Basa-Mabini Bonifacio', 'Dumangas', 1.7, 'No', 'TD-2006-1123', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Ernesto' AND last_name = 'Santiago'
UNION ALL SELECT submission_id, '1', 'Buenaflor Embarkadero', 'Dumangas', 2.8, 'No', NULL, 'No', FALSE, FALSE, TRUE, NULL, 'Diaz, Marcelo' FROM temp_farmer_ids WHERE first_name = 'Felicitas' AND last_name = 'Rivera'
UNION ALL SELECT submission_id, '1', 'Burgos-Regidor', 'Dumangas', 3.5, 'No', 'TD-2003-3344', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Marcelo' AND last_name = 'Diaz'
UNION ALL SELECT submission_id, '2', 'Burgos-Regidor', 'Dumangas', 2.0, 'No', 'TD-2005-3345', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Marcelo' AND last_name = 'Diaz'
UNION ALL SELECT submission_id, '1', 'Calao', 'Dumangas', 3.1, 'No', NULL, 'Yes', FALSE, TRUE, FALSE, 'Perez, Emilio', NULL FROM temp_farmer_ids WHERE first_name = 'Amparo' AND last_name = 'Gomez'
UNION ALL SELECT submission_id, '1', 'Cali', 'Dumangas', 4.0, 'No', 'TD-2002-5566', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Emilio' AND last_name = 'Perez'
UNION ALL SELECT submission_id, '2', 'Cali', 'Dumangas', 2.2, 'No', 'TD-2004-5567', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Emilio' AND last_name = 'Perez'
UNION ALL SELECT submission_id, '1', 'Cansilayan', 'Dumangas', 2.8, 'No', 'TD-2010-7788', 'Yes', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Remedios' AND last_name = 'Castro'
UNION ALL SELECT submission_id, '2', 'Cansilayan', 'Dumangas', 1.5, 'No', 'TD-2012-7789', 'No', TRUE, FALSE, FALSE, NULL, NULL FROM temp_farmer_ids WHERE first_name = 'Remedios' AND last_name = 'Castro';

-- Step 6: Display summary
DO $$
DECLARE
    new_farmers_count INTEGER;
    existing_farmers_count INTEGER;
    total_parcels_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO new_farmers_count FROM temp_sample_farmers;
    
    SELECT COUNT(*) INTO existing_farmers_count 
    FROM rsbsa_submission r
    INNER JOIN temp_sample_farmers t 
        ON r."FIRST NAME" = t.first_name 
        AND r."LAST NAME" = t.last_name
        AND r."BARANGAY" = t.barangay;
    
    SELECT COUNT(*) INTO total_parcels_count
    FROM rsbsa_farm_parcels p
    INNER JOIN temp_farmer_ids f ON p.submission_id = f.submission_id;
    
    RAISE NOTICE '========================================';
    RAISE NOTICE 'SAMPLE FARMERS INSERTION COMPLETE';
    RAISE NOTICE '========================================';
    RAISE NOTICE 'Farmers in sample data: %', new_farmers_count;
    RAISE NOTICE 'Farmers actually inserted: %', existing_farmers_count;
    RAISE NOTICE 'Farm parcels created: %', total_parcels_count;
    RAISE NOTICE '========================================';
    RAISE NOTICE 'NOTE: Duplicates were skipped based on';
    RAISE NOTICE 'matching First Name + Last Name + Barangay';
    RAISE NOTICE '========================================';
END $$;

-- Cleanup temp tables
DROP TABLE IF EXISTS temp_sample_farmers;
DROP TABLE IF EXISTS temp_farmer_ids;
